In [2]:
# import relaited librairies

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

 import datasets

In [3]:
# heavy metals from 2017 to 2020
hm1 = pd.read_excel('data/2017/HM/HM_2017_P1.xlsx')
hm2 = pd.read_excel('data/2017/HM/HM_2017_P2.xlsx')
hm3 = pd.read_excel('data/2017/HM/HM_2017_P3.xlsx')
hm4 = pd.read_excel('data/2017/HM/HM_2017_P4.xlsx')
hm5 = pd.read_excel('data/2018/HM/HM_2018_P1.xlsx')
hm6 = pd.read_excel('data/2018/HM/HM_2018_P2.xlsx')
hm7 = pd.read_excel('data/2018/HM/HM_2018_P3.xlsx')
hm8 = pd.read_excel('data/2018/HM/HM_2018_P4.xlsx')
hm9 = pd.read_excel('data/2019/HM/HM_2019_P1.xlsx')
hm10 = pd.read_excel('data/2019/HM/HM_2019_P2.xlsx')
hm11 = pd.read_excel('data/2019/HM/HM_2019_P3.xlsx')
hm12 = pd.read_excel('data/2019/HM/HM_2019_P4.xlsx')
hm13 = pd.read_excel('data/2020/HM/HM_2020_P1.xlsx')
hm14 = pd.read_excel('data/2020/HM/HM_2020_P2.xlsx')
hm15 = pd.read_excel('data/2020/HM/HM_2020_P3.xlsx')
hm16 = pd.read_excel('data/2020/HM/HM_2020_P4.xlsx')

In [4]:
list1 = [hm1, hm2, hm3, hm4, hm5, hm6, hm7, hm8, hm9, hm10, hm11, hm12, hm13, hm14, hm15, hm16]

# checking for columns dispositons
for i in list1:
    print(i.columns)

Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chromium', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chromium', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chromium', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chromium', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chrome', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chrome', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chrome', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chrome', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chrome', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chrome', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chrome', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chrome', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chrome', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chrome', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chrome', 'Zinc'],
      dtype='object')
Index(['REF....SUBSTANCE', 'PERIOD', 'Lead', 'Cadmium', 'Arsenic', 'Mercury',
       'Copper', 'Chrome', 'Zinc'],
      dtype='object')

In [5]:
# join the hm datasets
hm = pd.concat([hm1, hm2, hm3, hm4, hm5, hm6, hm7, hm8, hm9, hm10, hm11, hm12, hm13, hm14, hm15, hm16], axis=0)

In [6]:
hm

,REF....SUBSTANCE,PERIOD,Lead,Cadmium,Arsenic,Mercury,Copper,Chromium,Zinc,Chrome
0,B0017,2017/P1,0.081,0.810,0.000,0.0,5.5,0.032,40,NaN
1,B0019,2017/P1,0.062,0.360,0.000,0.0,8.5,0.029,33,NaN
2,B0021,2017/P1,0.150,0.610,0.000,0.0,7.0,0.038,37,NaN
3,B0023,2017/P1,0.067,0.350,0.000,0.0,6.9,0.031,37,NaN
4,B0037,2017/P1,0.120,0.070,0.000,0.0,5.6,0.052,35,NaN
...,...,...,...,...,...,...,...,...,...,...
19,F0035,2020/P4,0.049,0.150,0.093,0.0,6.3,NaN,54,0.087
20,F0065,2020/P4,1.400,0.085,0.081,0.0,11.0,NaN,37,0.340
21,F0067,2020/P4,0.047,0.090,0.000,0.0,5.1,NaN,21,0.049
22,F0071,2020/P4,0.000,0.075,0.035,0.0,5.0,NaN,33,0.056
23,F0073,2020/P4,0.058,0.025,0.000,0.0,7.6,NaN,34,0.064

In [7]:
hm.describe().T

,count,mean,std,min,25%,50%,75%,max
Lead,431.0,0.221285,0.322265,0.000,0.06250,0.130,0.24500,3.000
Cadmium,431.0,0.186947,0.221463,0.011,0.06000,0.110,0.22000,2.100
Arsenic,431.0,0.037369,0.040220,0.000,0.00000,0.037,0.05700,0.340
Mercury,431.0,0.000427,0.002567,0.000,0.00000,0.000,0.00000,0.042
Copper,431.0,7.972158,2.809016,0.000,6.60000,7.700,9.00000,37.000
Chromium,66.0,0.088727,0.144092,0.000,0.02725,0.044,0.11225,1.100
Zinc,431.0,38.679814,10.387808,15.000,32.00000,37.000,44.00000,108.000
Chrome,365.0,0.107748,0.091180,0.015,0.05100,0.081,0.12000,0.710

In [8]:
print(f'Shape of Heavy metal = {hm.shape}')

Shape of Heavy metal = (431, 10)

In [9]:
# null values
hm.isna().sum()

REF....SUBSTANCE      0
PERIOD                0
Lead                  0
Cadmium               0
Arsenic               0
Mercury               0
Copper                0
Chromium            365
Zinc                  0
Chrome               66
dtype: int64

in 2020, chromium = chrome then we have to join the two columns

In [10]:
# fill nan values of chrome with chromium values
hm['Chrome'].fillna(hm['Chromium'], inplace=True)

In [11]:
# drop chromium column
hm.drop('Chromium', axis=1, inplace=True)

In [12]:
# null values
hm.isna().sum()

REF....SUBSTANCE    0
PERIOD              0
Lead                0
Cadmium             0
Arsenic             0
Mercury             0
Copper              0
Zinc                0
Chrome              0
dtype: int64

In [13]:
print(f'Shape of Heavy metal = {hm.shape}')

Shape of Heavy metal = (431, 9)

In [14]:
hm.describe().T

         count       mean        std     min      25%     50%     75%      max
Lead     431.0   0.221285   0.322265   0.000   0.0625   0.130   0.245    3.000
Cadmium  431.0   0.186947   0.221463   0.011   0.0600   0.110   0.220    2.100
Arsenic  431.0   0.037369   0.040220   0.000   0.0000   0.037   0.057    0.340
Mercury  431.0   0.000427   0.002567   0.000   0.0000   0.000   0.000    0.042
Copper   431.0   7.972158   2.809016   0.000   6.6000   7.700   9.000   37.000
Zinc     431.0  38.679814  10.387808  15.000  32.0000  37.000  44.000  108.000
Chrome   431.0   0.104835   0.101110   0.000   0.0470   0.077   0.120    1.100

In [15]:
hm.sample(10)

,REF....SUBSTANCE,PERIOD,Lead,Cadmium,Arsenic,Mercury,Copper,Zinc,Chrome
14,B0077,2020/P2,0.067,0.015,0.032,0.0,6.4,32,0.056
9,B0077,2020/P4,0.040,0.160,0.000,0.0,6.3,28,0.061
20,F0065,2020/P4,1.400,0.085,0.081,0.0,11.0,37,0.340
8,B0043,2019/P3,0.230,0.034,0.048,0.0,7.8,35,0.088
21,B0158,2020/P3,0.180,0.460,0.000,0.0,8.9,48,0.066
1,B0039,2017/P3,0.096,0.062,0.100,0.0,7.2,36,0.060
20,B0152,2020/P3,0.270,0.070,0.034,0.0,7.6,29,0.110
3,B0023,2017/P4,0.065,0.740,0.000,0.0,9.1,36,0.026
22,F0027,2019/P1,0.045,0.089,0.000,0.0,6.9,34,0.034
11,F0027,2018/P4,0.110,0.089,0.044,0.0,4.6,22,0.060

In [16]:
# heatmap to check correlation between columns
# sns.heatmap(hm.corr(), cmap='coolwarm')

In [17]:
# pairplot
# sns.pairplot(hm.corr())

we can see that the most correlate columns are Mercury, Arsenic and Lead.

let's plot Lead  and Chrome and Lead and Arsenic

In [18]:
# plt.figure(figsize=(10, 8))
# sns.scatterplot(x='Lead', y='Chrome', data=hm)
# plt.xlabel('Lead')
# plt.ylabel('Chrome')
# plt.legend()
# plt.show()

Lead and Chrome have a linear relation. but when Lead = 0, the relation is different (vertical line)

In [19]:
# plt.figure(figsize=(10, 8))
# sns.scatterplot(x='Lead', y='Arsenic', data=hm)
# plt.xlabel('Lead')
# plt.ylabel('Arsenic')
# plt.legend()
# plt.show()

Similarly, we have a linear relation and when Arsenic=0, the relation change (horizontal line)

In [20]:
hm

,REF....SUBSTANCE,PERIOD,Lead,Cadmium,Arsenic,Mercury,Copper,Zinc,Chrome
0,B0017,2017/P1,0.081,0.810,0.000,0.0,5.5,40,0.032
1,B0019,2017/P1,0.062,0.360,0.000,0.0,8.5,33,0.029
2,B0021,2017/P1,0.150,0.610,0.000,0.0,7.0,37,0.038
3,B0023,2017/P1,0.067,0.350,0.000,0.0,6.9,37,0.031
4,B0037,2017/P1,0.120,0.070,0.000,0.0,5.6,35,0.052
...,...,...,...,...,...,...,...,...,...
19,F0035,2020/P4,0.049,0.150,0.093,0.0,6.3,54,0.087
20,F0065,2020/P4,1.400,0.085,0.081,0.0,11.0,37,0.340
21,F0067,2020/P4,0.047,0.090,0.000,0.0,5.1,21,0.049
22,F0071,2020/P4,0.000,0.075,0.035,0.0,5.0,33,0.056
23,F0073,2020/P4,0.058,0.025,0.000,0.0,7.6,34,0.064

In [21]:
hm.rename(columns={"REF....SUBSTANCE" : 'Site'}, inplace=True)

In [22]:
hm = hm.sort_values(by='Site')
hm

      Site   PERIOD   Lead  Cadmium  Arsenic  Mercury  Copper  Zinc  Chrome
0    B0012  2020/P1  0.880    0.290    0.048      0.0    11.0    51   0.140
0    B0012  2020/P2  0.650    0.230    0.000      0.0     8.7    48   0.110
0    B0012  2020/P3  0.890    0.160    0.059      0.0     7.2    43   0.140
0    B0012  2020/P4  0.630    0.640    0.053      0.0     9.1    40   0.160
0    B0017  2017/P1  0.081    0.810    0.000      0.0     5.5    40   0.032
..     ...      ...    ...      ...      ...      ...     ...   ...     ...
31  FE0001  2018/P3  0.089    0.400    0.058      0.0     7.5    25   0.047
34  FE0001  2018/P2  0.042    0.019    0.000      0.0     4.4    35   0.048
41  FE0001  2020/P1  0.052    0.055    0.000      0.0     6.7    39   0.051
16  FE0001  2017/P2  0.310    0.072    0.084      0.0     8.7    44   0.280
18  FE0001  2019/P4  0.000    0.036    0.000      0.0     9.4    36   0.069

[431 rows x 9 columns]

In [23]:
hm = hm.groupby(['Site'], as_index=False).mean()

In [24]:
# adding columns for MLR tresholds
hm['mlr_Lead'] = np.where(hm['Lead'] > 1.5, 1, 0)
hm['mlr_Cadmium'] = np.where(hm['Cadmium'] > 1, 1, 0)
hm['mlr_Arsenic'] = np.where(hm['Arsenic'] > 0.3, 1, 0)
hm['mlr_Mercury'] = np.where(hm['Mercury'] > 1, 1, 0)
hm['mlr_Copper'] = np.where(hm['Copper'] > 30, 1, 0)
hm['mlr_Zinc'] = np.where(hm['Zinc'] > 0, 1, 0)
hm['mlr_Chrome'] = np.where(hm['Chrome'] > 0, 1, 0)

In [25]:
hm.head(10)

,Site,Lead,Cadmium,Arsenic,Mercury,Copper,Zinc,Chrome,mlr_Lead,mlr_Cadmium,mlr_Arsenic,mlr_Mercury,mlr_Copper,mlr_Zinc,mlr_Chrome
0,B0012,0.762500,0.330000,0.040000,0.000000,9.000000,45.500000,0.137500,0,0,0,0,0,1,1
1,B0017,0.090000,0.334923,0.012769,0.000000,7.084615,35.615385,0.039692,0,0,0,0,0,1,1
2,B0019,0.137571,0.397643,0.033143,0.000357,7.142857,38.071429,0.066714,0,0,0,0,0,1,1
3,B0021,0.152929,0.498571,0.026429,0.000000,8.300000,37.857143,0.062929,0,0,0,0,0,1,1
4,B0023,0.116571,0.432857,0.013357,0.000000,8.078571,37.928571,0.065143,0,0,0,0,0,1,1
5,B0032,0.154917,0.199083,0.021917,0.000000,6.983333,37.333333,0.096333,0,0,0,0,0,1,1
6,B0037,0.153000,0.076667,0.033000,0.000000,7.375000,39.666667,0.094167,0,0,0,0,0,1,1
7,B0039,0.183750,0.072417,0.044833,0.000000,7.250000,38.833333,0.085500,0,0,0,0,0,1,1
8,B0041,0.201417,0.073167,0.061000,0.000000,7.675000,38.083333,0.160167,0,0,0,0,0,1,1
9,B0043,0.205917,0.091417,0.064417,0.000500,7.266667,36.083333,0.098833,0,0,0,0,0,1,1

In [26]:
hm_T = hm.pivot_table(columns='Site')

In [27]:
hm_T

Site,B0012,B0017,B0019,B0021,B0023,B0032,B0037,B0039,B0041,B0043,...,F0055,F0057,F0061,F0063,F0065,F0067,F0069,F0071,F0073,FE0001
Arsenic,0.0400,0.012769,0.033143,0.026429,0.013357,0.021917,0.033000,0.044833,0.061000,0.064417,...,0.014000,0.036667,0.013000,0.029667,0.065000,0.00000,0.0530,0.01625,0.01150,0.015833
Cadmium,0.3300,0.334923,0.397643,0.498571,0.432857,0.199083,0.076667,0.072417,0.073167,0.091417,...,0.064667,0.055000,0.166667,0.121333,0.070333,0.08425,0.0795,0.05800,0.03650,0.070500
Chrome,0.1375,0.039692,0.066714,0.062929,0.065143,0.096333,0.094167,0.085500,0.160167,0.098833,...,0.083333,0.148333,0.087000,0.148333,0.323333,0.04725,0.0690,0.04250,0.05300,0.097167
Copper,9.0000,7.084615,7.142857,8.300000,8.078571,6.983333,7.375000,7.250000,7.675000,7.266667,...,9.300000,10.900000,7.300000,8.533333,19.666667,6.12500,9.0000,5.62500,11.37500,7.458333
Lead,0.7625,0.090000,0.137571,0.152929,0.116571,0.154917,0.153000,0.183750,0.201417,0.205917,...,0.230000,0.137333,0.125667,0.254667,1.013333,0.04000,0.1040,0.01025,0.05275,0.096333
Mercury,0.0000,0.000000,0.000357,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000500,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0000,0.00000,0.00000,0.000000
Zinc,45.5000,35.615385,38.071429,37.857143,37.928571,37.333333,39.666667,38.833333,38.083333,36.083333,...,37.000000,32.333333,33.666667,35.000000,41.000000,32.25000,34.0000,34.75000,37.25000,36.000000
mlr_Arsenic,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0000,0.00000,0.00000,0.000000
mlr_Cadmium,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0000,0.00000,0.00000,0.000000
mlr_Chrome,1.0000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.0000,1.00000,1.00000,1.000000
mlr_Copper,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0000,0.00000,0.00000,0.000000
mlr_Lead,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0000,0.00000,0.00000,0.000000
mlr_Mercury,0.0000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.0000,0.00000,0.00000,0.000000
mlr_Zinc,1.0000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.0000,1.00000,1.00000,1.000000

In [28]:
surf_hm = pd.read_csv('data/surf_hm.csv', index_col=0)
surf_hm.head()

      Site  clc_1  clc_2  clc_3  clc_4  clc_5
115  B0012   85.4    4.1    3.6    0.0    6.9
406  B0017   24.9   22.6   52.5    0.0    0.0
421  B0019    0.0    0.0   94.6    5.4    0.0
417  B0021    0.0    3.8   82.9   13.3    0.0
394  B0023    2.8   12.9   58.7   25.6    0.0

In [29]:
surf_hm.shape

(60, 6)

In [30]:
hm_T.dot(surf_hm.set_index('Site'))

,clc_1,clc_2,clc_3,clc_4,clc_5
Arsenic,92.227329,82.193379,47.475387,1.412348,3.508591
Cadmium,326.417135,430.890222,299.109648,20.688248,10.287016
Chrome,296.647919,215.757346,103.343573,4.433923,11.549301
Copper,17015.156050,18722.363668,12752.681583,432.358690,479.527333
Lead,864.097604,372.354853,154.509878,8.957606,35.993100
Mercury,1.361387,0.316811,0.335271,0.007879,0.106681
Zinc,77403.897763,89072.015279,61523.134857,2082.065476,2770.481190
mlr_Arsenic,0.000000,0.000000,0.000000,0.000000,0.000000
mlr_Cadmium,0.000000,0.000000,0.000000,0.000000,0.000000
mlr_Chrome,1858.600000,2406.200000,1615.400000,54.200000,65.700000
mlr_Copper,0.000000,0.000000,0.000000,0.000000,0.000000
mlr_Lead,184.800000,0.000000,2.600000,0.700000,11.900000
mlr_Mercury,0.000000,0.000000,0.000000,0.000000,0.000000
mlr_Zinc,1858.600000,2406.200000,1615.400000,54.200000,65.700000

In [34]:
surf_hm.set_index('Site',inplace=True)
hm.set_index('Site',inplace=True)
total = [surf_hm, hm]
result = pd.concat(total, axis = 1)
result

,clc_1,clc_2,clc_3,clc_4,clc_5,Lead,Cadmium,Arsenic,Mercury,Copper,Zinc,Chrome,mlr_Lead,mlr_Cadmium,mlr_Arsenic,mlr_Mercury,mlr_Copper,mlr_Zinc,mlr_Chrome
Site,,,,,,,,,,,,,,,,,,,
B0012,85.4,4.1,3.6,0.0,6.9,0.762500,0.330000,0.040000,0.000000,9.000000,45.500000,0.137500,0,0,0,0,0,1,1
B0017,24.9,22.6,52.5,0.0,0.0,0.090000,0.334923,0.012769,0.000000,7.084615,35.615385,0.039692,0,0,0,0,0,1,1
B0019,0.0,0.0,94.6,5.4,0.0,0.137571,0.397643,0.033143,0.000357,7.142857,38.071429,0.066714,0,0,0,0,0,1,1
B0021,0.0,3.8,82.9,13.3,0.0,0.152929,0.498571,0.026429,0.000000,8.300000,37.857143,0.062929,0,0,0,0,0,1,1
B0023,2.8,12.9,58.7,25.6,0.0,0.116571,0.432857,0.013357,0.000000,8.078571,37.928571,0.065143,0,0,0,0,0,1,1
B0032,46.4,36.6,17.0,0.0,0.0,0.154917,0.199083,0.021917,0.000000,6.983333,37.333333,0.096333,0,0,0,0,0,1,1
B0037,28.4,66.7,4.9,0.0,0.0,0.153000,0.076667,0.033000,0.000000,7.375000,39.666667,0.094167,0,0,0,0,0,1,1
B0039,58.2,21.1,5.0,4.9,10.8,0.183750,0.072417,0.044833,0.000000,7.250000,38.833333,0.085500,0,0,0,0,0,1,1
B0041,50.5,49.5,0.0,0.0,0.0,0.201417,0.073167,0.061000,0.000000,7.675000,38.083333,0.160167,0,0,0,0,0,1,1
B0043,24.9,71.8,0.0,0.0,3.3,0.205917,0.091417,0.064417,0.000500,7.266667,36.083333,0.098833,0,0,0,0,0,1,1
B0045,45.4,32.7,8.7,4.3,8.9,0.246667,0.093083,0.058333,0.000000,8.225000,40.583333,0.192583,0,0,0,0,0,1,1
B0059,21.2,63.4,8.9,0.0,6.5,0.360000,0.423333,0.056333,0.000000,3.033333,46.666667,0.096667,0,0,0,0,0,1,1
B0061,2.1,9.5,88.4,0.0,0.0,0.095333,0.313067,0.016067,0.000000,7.766667,36.800000,0.069333,0,0,0,0,0,1,1
B0067,17.4,77.9,4.7,0.0,0.0,0.189600,0.554000,0.017200,0.000000,7.240000,31.800000,0.098000,0,0,0,0,0,1,1
B0069,16.2,80.4,3.4,0.0,0.0,0.130667,0.182083,0.026917,0.000000,7.550000,38.333333,0.093250,0,0,0,0,0,1,1
B0077,7.8,92.2,0.0,0.0,0.0,0.106800,0.171000,0.025800,0.000000,6.540000,33.000000,0.078800,0,0,0,0,0,1,1
B0093,14.4,80.1,5.5,0.0,0.0,0.095556,0.225556,0.012667,0.000000,8.377778,36.000000,0.087111,0,0,0,0,0,1,1
B0096,73.7,23.2,3.1,0.0,0.0,0.120000,0.130000,0.000000,0.000000,7.100000,33.000000,0.043000,0,0,0,0,0,1,1
B0103,23.4,47.3,29.3,0.0,0.0,0.576875,0.267687,0.079625,0.002063,8.275000,47.500000,0.130438,0,0,0,0,0,1,1
B0105,16.8,83.2,0.0,0.0,0.0,0.404667,0.114067,0.047467,0.000400,7.526667,38.733333,0.211333,0,0,0,0,0,1,1
B0116,94.9,0.0,5.1,0.0,0.0,0.325000,0.150000,0.038500,0.000000,10.500000,61.000000,0.125000,0,0,0,0,0,1,1
B0128,99.3,0.7,0.0,0.0,0.0,0.270000,0.740000,0.110000,0.000000,9.400000,43.000000,0.140000,0,0,0,0,0,1,1
B0140,97.8,0.0,0.0,0.0,2.2,0.658571,0.155857,0.069143,0.000714,9.600000,41.428571,0.262857,0,0,0,0,0,1,1
B0142,91.7,8.3,0.0,0.0,0.0,0.359000,0.171000,0.047000,0.004200,7.880000,38.200000,0.214000,0,0,0,0,0,1,1
B0152,75.7,19.5,4.8,0.0,0.0,0.238750,0.171625,0.033875,0.000000,7.187500,52.750000,0.086500,0,0,0,0,0,1,1
B0158,6.6,93.4,0.0,0.0,0.0,0.111000,0.555000,0.000000,0.000000,8.475000,41.250000,0.064250,0,0,0,0,0,1,1
B0163,100.0,0.0,0.0,0.0,0.0,1.700000,0.089500,0.085000,0.000000,11.925000,49.250000,0.267500,1,0,0,0,0,1,1
F0001,6.7,42.7,50.6,0.0,0.0,0.087750,0.075500,0.030875,0.000000,9.875000,35.875000,0.077125,0,0,0,0,0,1,1
F0003,4.8,9.1,86.1,0.0,0.0,0.059400,0.080000,0.021600,0.001000,6.720000,46.000000,0.047200,0,0,0,0,0,1,1
F0005,5.5,19.3,75.2,0.0,0.0,0.037714,0.075286,0.006571,0.000000,6.514286,34.857143,0.043429,0,0,0,0,0,1,1
F0007,0.0,53.8,46.2,0.0,0.0,0.036667,0.091833,0.082500,0.000000,7.800000,36.166667,0.057500,0,0,0,0,0,1,1
F0009,1.0,69.5,29.5,0.0,0.0,0.014857,0.225286,0.049571,0.000000,8.285714,36.428571,0.036286,0,0,0,0,0,1,1
F0011,4.5,35.6,59.9,0.0,0.0,0.042571,0.133143,0.052714,0.000000,6.900000,42.000000,0.039143,0,0,0,0,0,1,1
F0013,13.0,39.6,47.4,0.0,0.0,0.038571,0.093143,0.059000,0.000000,7.300000,40.285714,0.056143,0,0,0,0,0,1,1
F0015,4.4,0.0,95.6,0.0,0.0,0.068000,0.078800,0.074600,0.001000,8.520000,36.200000,0.088400,0,0,0,0,0,1,1
F0017,3.4,96.6,0.0,0.0,0.0,0.010500,0.258833,0.012833,0.000000,7.250000,31.166667,0.048667,0,0,0,0,0,1,1
F0019,49.4,40.0,10.7,0.0,0.0,0.191200,0.082200,0.014200,0.000900,9.400000,36.600000,0.089100,0,0,0,0,0,1,1
F0020,56.7,38.6,2.6,0.0,2.1,0.276600,0.063800,0.052100,0.001100,9.540000,38.800000,0.158400,0,0,0,0,0,1,1
F0021,4.2,63.1,32.7,0.0,0.0,0.058000,0.065500,0.067750,0.000000,10.225000,31.250000,0.073750,0,0,0,0,0,1,1
F0023,3.6,50.5,41.9,0.0,4.0,0.101500,0.272000,0.015250,0.000000,8.275000,33.000000,0.059250,0,0,0,0,0,1,1
F0025,5.8,23.2,71.0,0.0,0.0,0.062667,0.187667,0.012333,0.000000,9.333333,53.333333,0.051667,0,0,0,0,0,1,1
F0027,3.9,50.7,45.4,0.0,0.0,0.048818,0.145364,0.024000,0.000545,7.781818,37.181818,0.065273,0,0,0,0,0,1,1
F0029,34.0,60.3,5.7,0.0,0.0,0.354000,0.332000,0.066800,0.000000,7.680000,39.200000,0.090400,0,0,0,0,0,1,1
F0031,4.8,65.1,30.1,0.0,0.0,0.066000,0.210200,0.014600,0.000000,6.860000,33.000000,0.041800,0,0,0,0,0,1,1
F0033,0.4,20.3,79.3,0.0,0.0,0.010333,0.090500,0.007333,0.000000,8.416667,32.500000,0.039500,0,0,0,0,0,1,1
F0035,0.0,31.7,68.3,0.0,0.0,0.022900,0.116600,0.031900,0.000000,6.110000,39.700000,0.051600,0,0,0,0,0,1,1
F0037,84.8,0.0,2.6,0.7,11.9,1.765000,0.105333,0.099167,0.008500,8.133333,53.166667,0.460000,1,0,0,0,0,1,1
F0039,10.1,78.1,11.8,0.0,0.0,0.112000,0.074500,0.016000,0.000000,6.500000,35.000000,0.053000,0,0,0,0,0,1,1
F0041,56.9,43.1,0.0,0.0,0.0,0.465000,0.088750,0.070250,0.000000,8.850000,44.500000,0.202500,0,0,0,0,0,1,1
F0043,47.2,52.8,0.0,0.0,0.0,0.217500,0.107250,0.056500,0.000000,9.700000,34.750000,0.120250,0,0,0,0,0,1,1
F0055,46.3,40.7,13.0,0.0,0.0,0.230000,0.064667,0.014000,0.000000,9.300000,37.000000,0.083333,0,0,0,0,0,1,1
F0057,58.2,41.8,0.0,0.0,0.0,0.137333,0.055000,0.036667,0.000000,10.900000,32.333333,0.148333,0,0,0,0,0,1,1
F0061,40.1,24.7,35.2,0.0,0.0,0.125667,0.166667,0.013000,0.000000,7.300000,33.666667,0.087000,0,0,0,0,0,1,1
F0063,4.8,70.4,24.8,0.0,0.0,0.254667,0.121333,0.029667,0.000000,8.533333,35.000000,0.148333,0,0,0,0,0,1,1
F0065,100.0,0.0,0.0,0.0,0.0,1.013333,0.070333,0.065000,0.000000,19.666667,41.000000,0.323333,0,0,0,0,0,1,1
F0067,44.6,4.8,50.6,0.0,0.0,0.040000,0.084250,0.000000,0.000000,6.125000,32.250000,0.047250,0,0,0,0,0,1,1
F0069,22.8,73.6,3.6,0.0,0.0,0.104000,0.079500,0.053000,0.000000,9.000000,34.000000,0.069000,0,0,0,0,0,1,1
F0071,5.0,60.1,25.8,0.0,9.1,0.010250,0.058000,0.016250,0.000000,5.625000,34.750000,0.042500,0,0,0,0,0,1,1
F0073,0.0,14.4,85.6,0.0,0.0,0.052750,0.036500,0.011500,0.000000,11.375000,37.250000,0.053000,0,0,0,0,0,1,1
FE0001,5.8,91.1,3.1,0.0,0.0,0.096333,0.070500,0.015833,0.000000,7.458333,36.000000,0.097167,0,0,0,0,0,1,1